//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace device_controller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("device_controller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Alternator {
            get {
                object obj = ResourceManager.GetObject("Alternator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string device1_delaytime {
            get {
                return ResourceManager.GetString("device1_delaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v2.1.1.
        /// </summary>
        internal static string device1_firmwarever {
            get {
                return ResourceManager.GetString("device1_firmwarever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Projector.
        /// </summary>
        internal static string device1_name {
            get {
                return ResourceManager.GetString("device1_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P210.
        /// </summary>
        internal static string device1_productcode {
            get {
                return ResourceManager.GetString("device1_productcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        internal static string device1_startfreq {
            get {
                return ResourceManager.GetString("device1_startfreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 350.
        /// </summary>
        internal static string device1_switchingfreq {
            get {
                return ResourceManager.GetString("device1_switchingfreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5500.
        /// </summary>
        internal static string device2_actualspeed {
            get {
                return ResourceManager.GetString("device2_actualspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.
        /// </summary>
        internal static string device2_actualtorque {
            get {
                return ResourceManager.GetString("device2_actualtorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string device2_actualvoltage {
            get {
                return ResourceManager.GetString("device2_actualvoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v3.1.0.
        /// </summary>
        internal static string device2_firmwarever {
            get {
                return ResourceManager.GetString("device2_firmwarever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ford Alternator.
        /// </summary>
        internal static string device2_name {
            get {
                return ResourceManager.GetString("device2_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1300A.
        /// </summary>
        internal static string device2_productcode {
            get {
                return ResourceManager.GetString("device2_productcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Movie_Projector {
            get {
                object obj = ResourceManager.GetObject("Movie_Projector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
